#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
#  EC2 BOOTSTRAP for Udumula's Grand LMS
#  Run ONCE on a fresh Ubuntu 22.04+ EC2 instance to set up the host
#  for the GitHub Actions auto-deploy workflow.
#
#  Usage on the EC2 instance (as the ubuntu user):
#      curl -fsSL https://raw.githubusercontent.com/<your-repo>/main/ec2-bootstrap.sh | bash
#  OR copy this file over and run:
#      bash ec2-bootstrap.sh
#
#  After this completes, push to main / master on GitHub and it auto-deploys.
# ════════════════════════════════════════════════════════════════════
set -euo pipefail

APP_DIR="/opt/rusto-lms"
APP_USER="${SUDO_USER:-${USER:-ubuntu}}"

echo "════════════════════════════════════════════════════════════"
echo "  Udumula's Grand LMS — EC2 Bootstrap"
echo "  App dir: $APP_DIR"
echo "  Owner:   $APP_USER"
echo "════════════════════════════════════════════════════════════"

# 1. System update + base packages (NO host nginx — we use a container)
echo ""
echo ">> [1/5] Updating system packages..."
sudo apt-get update -y
sudo apt-get install -y curl ca-certificates gnupg lsb-release ufw rsync git \
                        openssl

# Make absolutely sure host nginx is not running on port 80
if dpkg -l nginx 2>/dev/null | grep -q ^ii ; then
  sudo systemctl stop nginx 2>/dev/null || true
  sudo systemctl disable nginx 2>/dev/null || true
fi

# 2. Install Docker (official)
if ! command -v docker > /dev/null 2>&1; then
  echo ""
  echo ">> [2/5] Installing Docker..."
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
       https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get update -y
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io \
                          docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker "$APP_USER"
  echo "   ✓ Docker installed; '$APP_USER' added to docker group (re-login required)"
else
  echo ">> [2/5] Docker already installed ✓"
fi

# 3. App directory
echo ""
echo ">> [3/5] Creating $APP_DIR ..."
sudo mkdir -p "$APP_DIR"
sudo chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
mkdir -p "$APP_DIR/nginx/conf.d" "$APP_DIR/nginx/certs"

# 4. Generate .env.production from template if missing
if [ ! -f "$APP_DIR/.env.production" ]; then
  echo ""
  echo ">> [4/5] Generating $APP_DIR/.env.production ..."
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  JWT_SECRET=$(openssl rand -hex 48)
  PUBLIC_HOST=$(curl -fsS http://169.254.169.254/latest/meta-data/public-hostname 2>/dev/null \
                || hostname -f 2>/dev/null || echo "localhost")

  cat > "$APP_DIR/.env.production" <<EOF
# ─────────── Auto-generated by ec2-bootstrap.sh — DO NOT COMMIT ───────────
POSTGRES_USER=lms
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=rusto_lms
DATABASE_URL=postgresql://lms:${POSTGRES_PASSWORD}@db:5432/rusto_lms

JWT_SECRET_KEY=${JWT_SECRET}
DEFAULT_ADMIN_USERNAME=admin
DEFAULT_ADMIN_PASSWORD=Admin@1234

# Comma-separated origins allowed to call the API.
# Edit this to your real domain(s) before going live.
CORS_ORIGINS=http://${PUBLIC_HOST},http://localhost

# Frontend reads VITE_API_URL at build time; nginx routes /api -> backend
VITE_API_URL=/api

# Optional AI agent keys (uncomment + fill to enable full LLM mode)
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# AGENT_PROVIDER=auto

TZ=Asia/Kolkata
EOF
  chmod 600 "$APP_DIR/.env.production"
  echo "   ✓ Wrote $APP_DIR/.env.production"
  echo "   ⚠ Review CORS_ORIGINS once you point a real domain."
else
  echo ">> [4/5] .env.production already exists ✓ (leaving untouched)"
fi

# 5. Firewall
echo ""
echo ">> [5/5] Configuring firewall..."
sudo ufw allow OpenSSH > /dev/null
sudo ufw allow 80/tcp > /dev/null
sudo ufw allow 443/tcp > /dev/null
sudo ufw --force enable > /dev/null
echo "   ✓ UFW: ssh, 80, 443 allowed"

cat <<EOF

════════════════════════════════════════════════════════════
  Bootstrap complete!

  Next steps:

  1. Add these GitHub repository secrets (Settings → Secrets):
        EC2_HOST       ← your EC2 public DNS or IP
        EC2_USER       ← $APP_USER
        EC2_SSH_KEY    ← contents of the private key matching the
                         pubkey in ~/.ssh/authorized_keys on EC2

  2. (Optional) Edit $APP_DIR/.env.production:
        - Set CORS_ORIGINS to your real domain(s)
        - Add ANTHROPIC_API_KEY for the AI agent

  3. Push to main / master — the workflow auto-deploys.

  4. (Optional) HTTPS with Let's Encrypt:
        sudo apt-get install certbot
        sudo certbot certonly --standalone -d your-domain.example.com
        # then edit nginx/conf.d/default.conf to add a 443 server block
        # and mount /etc/letsencrypt into the nginx container.

  Default admin login: admin / Admin@1234   ← CHANGE IT IMMEDIATELY
════════════════════════════════════════════════════════════
EOF
