#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
# Rusto LMS — EC2 Bootstrap (run ONCE on a fresh Ubuntu 22.04 instance)
#
# What this does:
#   1. Configures 2GB swap
#   2. Installs Docker + Docker Compose v2
#   3. Configures UFW firewall (80, 443, 22 only)
#   4. Creates /opt/rusto-lms with correct permissions
#   5. Generates .env.production from your inputs
#   6. Configures log rotation
#
# Usage (on EC2 as ubuntu user):
#   bash ec2-bootstrap.sh
# ════════════════════════════════════════════════════════════════════
set -euo pipefail

APP_DIR="/opt/rusto-lms"
APP_USER="${SUDO_USER:-${USER:-ubuntu}}"
CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'

echo -e "${CYAN}"
echo "════════════════════════════════════════════════════════════"
echo "  Rusto LMS — EC2 Bootstrap"
echo "  App dir: $APP_DIR"
echo "  Owner:   $APP_USER"
echo "════════════════════════════════════════════════════════════"
echo -e "${NC}"

# ── 1. Swap ─────────────────────────────────────────────────────────
echo -e "${CYAN}[1/6] Configuring 2 GB swap...${NC}"
if ! swapon --show | grep -q "/swapfile"; then
  sudo fallocate -l 2G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile
  sudo swapon /swapfile
  echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
  echo "  ✓ 2 GB swap enabled"
else
  echo "  ✓ Swap already configured"
fi

# ── 2. System packages ───────────────────────────────────────────────
echo -e "${CYAN}[2/6] Installing system packages...${NC}"
sudo apt-get update -y
sudo apt-get install -y curl ca-certificates gnupg lsb-release ufw rsync git openssl

# Stop host nginx (we use containerized nginx)
sudo systemctl stop nginx 2>/dev/null || true
sudo systemctl disable nginx 2>/dev/null || true

# ── 3. Docker ────────────────────────────────────────────────────────
echo -e "${CYAN}[3/6] Installing Docker...${NC}"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sudo bash
  sudo usermod -aG docker "$APP_USER"
  echo "  ✓ Docker installed"
else
  echo "  ✓ Docker already installed"
fi

# Ensure Docker Compose v2
if ! docker compose version >/dev/null 2>&1; then
  sudo apt-get install -y docker-compose-plugin
fi
echo "  ✓ Docker Compose: $(docker compose version --short)"

# ── 4. Firewall ──────────────────────────────────────────────────────
echo -e "${CYAN}[4/6] Configuring firewall...${NC}"
sudo ufw --force reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp   comment "SSH"
sudo ufw allow 80/tcp   comment "HTTP"
sudo ufw allow 443/tcp  comment "HTTPS"
sudo ufw --force enable
echo "  ✓ UFW: 22, 80, 443 open"

# ── 5. App directory ─────────────────────────────────────────────────
echo -e "${CYAN}[5/6] Creating app directory...${NC}"
sudo mkdir -p "$APP_DIR"
sudo chown -R "$APP_USER":"$APP_USER" "$APP_DIR"
mkdir -p "$APP_DIR/nginx/conf.d" "$APP_DIR/nginx/certs"
echo "  ✓ $APP_DIR ready"

# ── 6. .env.production ───────────────────────────────────────────────
echo -e "${CYAN}[6/6] Creating .env.production...${NC}"
if [ -f "$APP_DIR/.env.production" ]; then
  echo -e "${YELLOW}  .env.production already exists — skipping${NC}"
else
  # Generate a secure JWT secret
  JWT_SECRET=$(openssl rand -hex 32)
  DB_PASSWORD=$(openssl rand -hex 16)

  cat > "$APP_DIR/.env.production" << ENVEOF
# Auto-generated by ec2-bootstrap.sh
# Fill in your real credentials below

POSTGRES_USER=lms
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=rusto_lms
DATABASE_URL=postgresql://lms:${DB_PASSWORD}@db:5432/rusto_lms

JWT_SECRET_KEY=${JWT_SECRET}
JWT_EXPIRE_HOURS=8

DEFAULT_ADMIN_USERNAME=admin
DEFAULT_ADMIN_PASSWORD=CHANGE_THIS_before_first_deploy

# Add your real domain names
CORS_ORIGINS=http://localhost,http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo localhost)

# Razorpay
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=

# SMS
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
MSG91_AUTH_KEY=
MSG91_SENDER_ID=

# Email
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=
SMTP_FROM_NAME=Rusto LMS

# AI
ANTHROPIC_API_KEY=
AGENT_PROVIDER=auto

VITE_API_URL=/api
TZ=Asia/Kolkata
ENVEOF
  chmod 600 "$APP_DIR/.env.production"
  echo "  ✓ .env.production created at $APP_DIR/.env.production"
  echo -e "${YELLOW}  ⚠  Edit .env.production and add your real credentials before deploying!${NC}"
fi

# ── Log rotation ─────────────────────────────────────────────────────
sudo tee /etc/logrotate.d/docker-containers > /dev/null << 'LOGROTEOF'
/var/lib/docker/containers/*/*.log {
  daily
  rotate 7
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
LOGROTEOF

# ── Done ─────────────────────────────────────────────────────────────
PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || echo "YOUR_IP")

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  ✓ EC2 Bootstrap complete!                                ${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Edit credentials:"
echo -e "     ${YELLOW}nano $APP_DIR/.env.production${NC}"
echo ""
echo "  2. Add these GitHub Secrets in your repo Settings → Secrets → Actions:"
echo -e "     ${CYAN}EC2_HOST${NC}     = $PUBLIC_IP"
echo -e "     ${CYAN}EC2_USER${NC}     = $APP_USER"
echo -e "     ${CYAN}EC2_SSH_KEY${NC}  = (contents of your .pem file)"
echo ""
echo "  3. Push to main/master to trigger auto-deploy:"
echo -e "     ${CYAN}git push origin main${NC}"
echo ""
echo -e "  App will be available at: ${CYAN}http://$PUBLIC_IP${NC}"
echo ""
