import React from "react";
import { useParams, Link } from "react-router-dom";
import { FileText, Shield, ArrowLeft } from "lucide-react";

/**
 * RustoLegal — Terms of Service and Privacy Policy pages.
 * Served at /terms and /privacy within the Rusto customer-facing site.
 */

const TERMS = {
  title: "Terms of Service",
  icon: FileText,
  updated: "June 2025",
  sections: [
    {
      heading: "1. Acceptance of Terms",
      body: "By accessing or using Rusto's platform, website, or mobile application, you agree to these Terms. If you are using Rusto on behalf of a business, you agree to these Terms on behalf of that business.",
    },
    {
      heading: "2. Booking & Reservations",
      body: "When you book a property through Rusto, you enter a direct agreement with the property owner. Rusto acts as an intermediary platform. All bookings are subject to the individual property's policies displayed at the time of reservation. Rusto is not liable for disputes between guests and property owners.",
    },
    {
      heading: "3. Payments",
      body: "Payments are processed securely via Razorpay. Rusto does not store your payment card details. The amount charged is the amount displayed at checkout, inclusive of applicable taxes. Promotional discounts are applied before payment and are subject to the specific promo code's terms.",
    },
    {
      heading: "4. Cancellations & Refunds",
      body: "Cancellation policies are set by individual properties and displayed on each listing. Refunds, where applicable, are processed within 5-7 business days to the original payment method. Rusto's platform fee (if any) is non-refundable.",
    },
    {
      heading: "5. Membership & Rewards",
      body: "Rusto Points are earned on confirmed and paid bookings. Points have no cash value and cannot be transferred. Rusto reserves the right to modify the Membership programme with 30 days' notice. Points expire after 24 months of account inactivity.",
    },
    {
      heading: "6. User Conduct",
      body: "You agree not to misuse the platform, post false reviews, or engage in any activity that disrupts the service. Rusto reserves the right to suspend accounts found in violation of these Terms.",
    },
    {
      heading: "7. Intellectual Property",
      body: "All content on the Rusto platform — including the brand, logos, designs, and software — is the property of Tygonix Global Consulting LLC. You may not reproduce, distribute, or create derivative works without written permission.",
    },
    {
      heading: "8. Limitation of Liability",
      body: "Rusto's liability is limited to the booking amount paid for a specific reservation. Rusto is not liable for indirect, incidental, or consequential damages arising from use of the platform.",
    },
    {
      heading: "9. Governing Law",
      body: "These Terms are governed by the laws of India. Disputes shall be resolved through arbitration in accordance with the Arbitration and Conciliation Act, 1996, with the seat of arbitration in Andhra Pradesh, India.",
    },
    {
      heading: "10. Contact Us",
      body: "For questions about these Terms, email us at legal@rusto.in or write to: Tygonix Global Consulting LLC, Kotappakonda, Andhra Pradesh, India.",
    },
  ],
};

const PRIVACY = {
  title: "Privacy Policy",
  icon: Shield,
  updated: "June 2025",
  sections: [
    {
      heading: "1. Information We Collect",
      body: "We collect information you provide directly (name, phone, email, payment details) and information generated by your use of Rusto (booking history, search queries, device information, and cookies).",
    },
    {
      heading: "2. How We Use Your Information",
      body: "We use your information to: process bookings and payments; send booking confirmations and travel updates; improve our platform; personalise your experience; run the Membership & Rewards programme; comply with legal obligations; and send marketing communications (opt-out available).",
    },
    {
      heading: "3. Information Sharing",
      body: "We share your information with: the property you book (name, phone, special requests); payment processors (Razorpay) for secure transactions; analytics providers (aggregated, anonymised data only); law enforcement when required by law. We do not sell your personal data.",
    },
    {
      heading: "4. Data Security",
      body: "We implement industry-standard security measures including encryption in transit (TLS 1.2+), secure storage, and access controls. However, no internet transmission is 100% secure, and we cannot guarantee absolute security.",
    },
    {
      heading: "5. Cookies",
      body: "We use essential cookies (required for the platform to function) and analytics cookies (to understand usage patterns). You can disable non-essential cookies through your browser settings. Disabling cookies may affect some platform features.",
    },
    {
      heading: "6. Your Rights",
      body: "Under applicable law, you have the right to: access your personal data; correct inaccurate data; request deletion of your account and associated data; opt out of marketing communications; and port your data. To exercise these rights, contact privacy@rusto.in.",
    },
    {
      heading: "7. Data Retention",
      body: "We retain your account data for as long as your account is active. Booking records are retained for 7 years for accounting and legal compliance. You may request deletion of your account, after which personal data is anonymised within 90 days.",
    },
    {
      heading: "8. Third-Party Links",
      body: "Our platform may link to third-party websites. We are not responsible for the privacy practices of those websites and encourage you to review their privacy policies.",
    },
    {
      heading: "9. Children's Privacy",
      body: "Rusto does not knowingly collect personal information from children under 13. If you believe a child has provided us with personal information, contact us at privacy@rusto.in.",
    },
    {
      heading: "10. Contact & Grievance",
      body: "For privacy concerns or to exercise your data rights: Email privacy@rusto.in | Grievance Officer: support@rusto.in | Address: Tygonix Global Consulting LLC, Kotappakonda, Andhra Pradesh 522302, India.",
    },
  ],
};

export function RustoTerms()   { return <LegalPage page={TERMS}/>; }
export function RustoPrivacy() { return <LegalPage page={PRIVACY}/>; }

function LegalPage({ page }) {
  const Icon = page.icon;
  return (
    <div className="max-w-3xl mx-auto px-4 py-10 animate-fade-in rusto-page-light">
      {/* Back */}
      <Link to="/" className="inline-flex items-center gap-1.5 text-sm mb-6 transition-colors" style={{color:"var(--ink-500, #6b7280)"}}>
        <ArrowLeft size={14}/> Back to home
      </Link>

      {/* Header */}
      <div className="flex items-start gap-4 mb-8">
        <div className="w-12 h-12 rounded-2xl bg-navy/10 flex items-center justify-center shrink-0">
          <Icon size={24} style={{color:"var(--c-navy, #1B2A4A)"}}/>
        </div>
        <div>
          <h1 className="font-display text-3xl font-bold" style={{color:"var(--c-navy, #1B2A4A)"}}>{page.title}</h1>
          <p className="text-sm mt-1" style={{color:"var(--ink-500, #667085)"}}>Last updated: {page.updated}</p>
        </div>
      </div>

      {/* Sections */}
      <div className="space-y-6">
        {page.sections.map((s, i) => (
          <div key={i} className="bg-white border border-ivory-200 rounded-2xl p-6">
            <h2 className="font-display text-base font-bold mb-2" style={{color:"var(--c-navy, #1B2A4A)"}}>{s.heading}</h2>
            <p className="text-sm leading-relaxed" style={{color:"var(--ink-700, #344054)"}}>{s.body}</p>
          </div>
        ))}
      </div>

      {/* Footer note */}
      <div className="mt-8 p-4 bg-navy/5 rounded-xl border border-navy/10 text-center">
        <p className="text-xs" style={{color:"var(--ink-500, #667085)"}}>
          Questions? Email us at <a href="mailto:legal@rusto.in" className="text-gold hover:underline font-semibold">legal@rusto.in</a>
        </p>
      </div>
    </div>
  );
}
