# ════════════════════════════════════════════════════════════════════
#  RDS for PostgreSQL. Private (no public access), in the private
#  subnets, reachable only from the app security group. Password is
#  generated by Terraform and never printed in plaintext to logs.
# ════════════════════════════════════════════════════════════════════

locals {
  name = "${var.project}-${var.environment}"
}

resource "aws_db_subnet_group" "this" {
  name       = "${local.name}-db-subnets"
  subnet_ids = var.private_subnet_ids
  tags       = { Name = "${local.name}-db-subnets" }
}

# Generate a strong password with only URL-safe characters so the
# DATABASE_URL connection string never needs URL-encoding.
resource "random_password" "db" {
  length  = 28
  special = false
}

# Stable suffix for the final snapshot name (timestamp() would change on
# every plan and force perpetual diffs). random_id is generated once and
# persists in state.
resource "random_id" "snapshot" {
  byte_length = 4
}

resource "aws_db_instance" "this" {
  identifier     = "${local.name}-db"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage     = var.allocated_storage
  max_allocated_storage = var.allocated_storage * 3
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.rds_sg_id]
  publicly_accessible    = false

  backup_retention_period   = var.backup_retention_days
  skip_final_snapshot       = !var.production_grade
  final_snapshot_identifier = var.production_grade ? "${local.name}-final-${random_id.snapshot.hex}" : null
  deletion_protection       = var.production_grade
  multi_az                  = var.production_grade

  apply_immediately = true
  tags              = { Name = "${local.name}-db" }

  lifecycle {
    # engine_version is set to a major version (e.g. "16"); RDS resolves it
    # to the latest available minor (e.g. 16.9). Ignore that so later plans
    # don't try to revert it.
    ignore_changes = [engine_version]
  }
}
